-- CreateEnum
CREATE TYPE "PFDefinition" AS ENUM ('PETSHOP', 'BANHO_TOSA', 'CLINICA_VETERINARIA', 'PENSANDO_NEGOCIO', 'VENDAS_ONLINE', 'OUTRO_RAMO', 'CONSUMIDOR_FINAL', 'VENDEDOR_REPRESENTANTE', 'DROPSHIPPING');

-- CreateEnum
CREATE TYPE "PJDefinition" AS ENUM ('PETSHOP', 'BANHO_TOSA', 'CLINICA_VETERINARIA', 'PENSANDO_NEGOCIO', 'VENDAS_ONLINE', 'OUTRO_RAMO', 'CONSUMIDOR_FINAL', 'VENDEDOR_REPRESENTANTE', 'DROPSHIPPING');

-- AlterTable
ALTER TABLE "Address" ADD COLUMN     "district" TEXT,
ADD COLUMN     "label" TEXT;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "alternatePhone" TEXT,
ADD COLUMN     "marketingOptIn" BOOLEAN,
ADD COLUMN     "pfDefinition" "PFDefinition",
ADD COLUMN     "pjDefinition" "PJDefinition",
ADD COLUMN     "stateRegistrationIsento" BOOLEAN;
